kind: Deployment
apiVersion: apps/v1
metadata:
   name: harsh
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: harsh
   template:
      metadata:
        labels:
          app: harsh
      spec:
       containers:
        - name: harsh
          image: harshproject1:Sv1
          imagePullPolicy: Always
          ports:
          - containerPort: 80