kind: Service                             
apiVersion: v1
metadata:
  name: harsh
  labels:
    app: harsh
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: harsh                   
  type: LoadBalancer      